### ISSUE TITLE
Reconocimiento facial

### ISSUE THREAD

**Issue by vfrico** [albertcp/Kare#3]

**Comment by eamadord** [comment]
Para llamarlo desde consola con Curl:

1. Creamos un fichero .json (myparams.json, por ejemplo) cuyo contenido sea:
_{
  "classifier_ids": ["FacexUnlocker_712241985"]
}_

2. Ejecutamos el comando 
_curl -X POST --form "images_file=@{imagen_a_probar}" --form "parameters=@myparams.json" "https://gateway-a.watsonplatform.net/visual-recognition/api/v3/classify?api_key=8ff2c939bc18db412b00bb5f87f16d04b5890209&version=2016-05-20"_
