### ISSUE TITLE
Reconocimiento de voz

### ISSUE THREAD

**Issue by vfrico** [albertcp/Kare#4]

**Comment by eamadord** [comment]
Necesitamos conocer el formato del audio (en este caso es flac)

curl -X POST u f17c23ce-4971-4bb2-b695-2679f7639875:1zltSPoAcFyL \
--header "Content-Type: audio/{audio_type}" \
 --data-binary @{audio_file} "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize"
